logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: 'true'
    gateway:
      routes:
      - id: delivery-service
        uri: lb://delivery-service
        predicates:
          - Path=/api/deliveries/**
        filters:
          - name: CircuitBreaker
            args:
              name: delivery
              fallbackUri: forward:/fallbacks/delivery



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: 'true'
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    delivery:
      registerHealthIndicator: true
      event-consumer-buffer-size: 10
      slidingWindowSize: 5
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
